# Generated by Django 4.2.29 on 2026-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_community_dwelling_maintenanceupdate_repairrequest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='repairrequest',
            options={'ordering': ['-reported_at']},
        ),
        migrations.AlterField(
            model_name='maintenanceupdate',
            name='status_snapshot',
            field=models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
