# Generated by Django 4.2.29 on 2026-04-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alter_maintenanceupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
    ]
