# Generated by Django 6.0.4 on 2026-04-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alter_maintenanceupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
    ]
